#!/usr/bin/env bash
# created: 2026-07-28 | branch: feat/qrm-s7-vendor-artifacts
# author: Claude Opus 4.8 (1M context), directed by @SaulBuilds
# status: active
#
# vendor-template-artifacts.sh — copy the AUDITED creation code of the eight
# governance templates out of citrate-chain and into this app, and prove each
# one hashes to the value registered on chain.
#
# WHY THIS EXISTS
#
# GovernanceProtocolFactory.deployProtocol takes the creation code as an
# argument and refuses it unless `keccak256(creationCode)` equals the
# `initCodeHash` the registry pinned (GF-2). So this app cannot deploy a
# governance protocol without carrying the exact audited bytes — it cannot
# derive them, and it must not invent them.
#
# WHY IT VERIFIES AGAINST THE CHAIN RATHER THAN THE BUILD
#
# Copying a file out of `forge` output proves only that the copy matches
# whatever was compiled locally, which may not be what was registered — a
# different compiler version, a dirty tree, or an edited source all produce
# bytes that look fine and fail GF-2 at the ceremony, after a human has already
# approved. So every artifact is checked against `get(templateId).initCodeHash`
# read from the LIVE registry. A mismatch fails this script loudly, here, where
# it is cheap.
#
# Usage:
#   scripts/vendor-template-artifacts.sh [path-to-citrate-chain]
#
# Env:
#   RPC_URL   default https://rpc.citrate.ai
set -euo pipefail

CHAIN="${1:-../citrate-chain}"
RPC_URL="${RPC_URL:-https://rpc.citrate.ai}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT="$ROOT/src-tauri/artifacts/templates"
CONTRACTS="$CHAIN/contracts"

TEMPLATES=(
  ThresholdApproval
  ClassificationGate
  BudgetedAutonomy
  SegregationOfDuties
  TimeBoundedElevation
  ChangeControlBoard
  SupplierAdmission
  IncidentEscalation
)

[ -d "$CONTRACTS/out" ] || {
  echo "no forge output at $CONTRACTS/out — run \`forge build\` in citrate-chain first" >&2
  exit 2
}

REGISTRY="$(uv run python3 -c "
import json
print(json.load(open('$CONTRACTS/addresses/40204.json'))['contracts']['GovernanceTemplateRegistry'])
")"
[ -n "$REGISTRY" ] || { echo "GovernanceTemplateRegistry is not in the address book" >&2; exit 2; }

echo ">>> registry $REGISTRY on $RPC_URL"
mkdir -p "$OUT"

fail=0
for t in "${TEMPLATES[@]}"; do
  art="$CONTRACTS/out/$t.sol/$t.json"
  [ -f "$art" ] || { echo "  MISSING artifact: $art"; fail=1; continue; }

  code="$(uv run python3 -c "
import json
print(json.load(open('$art'))['bytecode']['object'])
")"
  local_hash="$(cast keccak "$code")"

  id="$(cast call "$REGISTRY" 'templateId(string,uint32)(bytes32)' "$t" 1 --rpc-url "$RPC_URL")"
  chain_hash="$(cast call "$REGISTRY" \
    'get(bytes32)((bytes32,string,uint32,bytes32,bytes32,string,bool,uint64))' \
    "$id" --rpc-url "$RPC_URL" 2>/dev/null | tr -d '()' | cut -d, -f4 | tr -d ' ')"

  if [ "$local_hash" != "$chain_hash" ]; then
    echo "  MISMATCH $t"
    echo "     local $local_hash"
    echo "     chain $chain_hash"
    echo "     the bytes here are NOT the bytes that were registered — do not vendor them"
    fail=1
    continue
  fi

  printf '%s\n' "$code" > "$OUT/$t.hex"
  printf '  %-22s %s  (%s bytes)\n' "$t" "$local_hash" "$(( (${#code} - 2) / 2 ))"
done

[ "$fail" -eq 0 ] || { echo ">>> REFUSING to vendor: at least one artifact does not match the chain" >&2; exit 1; }

# The pinned hashes the Rust test asserts against, regenerated here so the test
# and the artifacts cannot drift apart silently.
{
  echo "// Generated by scripts/vendor-template-artifacts.sh — do not edit by hand."
  echo "//"
  echo "// Test-only: this table exists to be asserted against, so lib.rs gates it"
  echo "// behind #[cfg(test)]. Its job is done at test time — if the embedded"
  echo "// bytecode ever stops matching what the registry pinned, the build fails"
  echo "// here rather than the factory refusing the deploy in front of a human."
  echo "// Each value is the initCodeHash REGISTERED ON CHAIN for that template,"
  echo "// read from GovernanceTemplateRegistry at vendoring time. The test in"
  echo "// deploy.rs asserts the embedded artifact hashes to exactly this."
  echo "pub const REGISTERED_INIT_CODE_HASHES: &[(&str, &str)] = &["
  for t in "${TEMPLATES[@]}"; do
    id="$(cast call "$REGISTRY" 'templateId(string,uint32)(bytes32)' "$t" 1 --rpc-url "$RPC_URL")"
    h="$(cast call "$REGISTRY" \
      'get(bytes32)((bytes32,string,uint32,bytes32,bytes32,string,bool,uint64))' \
      "$id" --rpc-url "$RPC_URL" 2>/dev/null | tr -d '()' | cut -d, -f4 | tr -d ' ')"
    echo "    (\"$t\", \"$h\"),"
  done
  echo "];"
} > "$ROOT/src-tauri/src/template_hashes.rs"

echo ">>> vendored ${#TEMPLATES[@]} artifacts to src-tauri/artifacts/templates/"
echo ">>> wrote src-tauri/src/template_hashes.rs"
echo ">>> every one verified against the live registry"
