// Generated by scripts/vendor-template-artifacts.sh — do not edit by hand.
//
// Test-only: lib.rs gates this table behind #[cfg(test)]. The test in
// deploy.rs asserts every embedded artifact hashes to exactly its row, and
// scripts/verify-template-hashes.sh proves each row equals a fresh build of
// CHAIN_REV with the pinned toolchain.
//
// Source: rows named in BUILT_FROM_CHAIN_REV were BUILT from citrate-chain
// 0721f4b0a7064d59c4fdeacae2f18170792c772c with forge 1.8.3 and solc 0.8.36
// (--from-build) and are NOT yet registered: register them, then re-vendor
// without --from-build. Every other row was read from
// GovernanceTemplateRegistry when it was last vendored.
pub const CHAIN_REV: &str = "0721f4b0a7064d59c4fdeacae2f18170792c772c";
pub const FORGE_VERSION: &str = "1.8.3";
pub const SOLC_VERSION: &str = "0.8.36";
/// Templates whose row is a build of CHAIN_REV, not (yet) a registry read.
pub const BUILT_FROM_CHAIN_REV: &[&str] = &[
    "ThresholdApproval",
    "SegregationOfDuties",
    "ChangeControlBoard",
    "SupplierAdmission",
];
pub const PINNED_INIT_CODE_HASHES: &[(&str, &str)] = &[
    ("ThresholdApproval", "0x2ec7b334ce9c2e7c26c14afcb01e51a62bc70a0880bee3b8260b8c87aade99d1"),
    ("ClassificationGate", "0x28a8469e93680b108bc7297f33b8450372f15b71647ba7fb770b336dd544fc84"),
    ("BudgetedAutonomy", "0xfff789db4ef080711f9ea1cc389932043fac900aeba3e388ec9d1c56d3619953"),
    ("SegregationOfDuties", "0xd7c4b7842ec5888c5c30dce5e8f7c6685734ce7a93f408feb5a439e87c05be17"),
    ("TimeBoundedElevation", "0x560ed4d97e847e2b8373a69e3e648e86b95561035eb86992eab1d87a96b226ed"),
    ("ChangeControlBoard", "0xc945163c3fd7d66ce521ab386d12c6f099cfd8ebf97456d65e9bcbb7ca92360a"),
    ("SupplierAdmission", "0x1100ef1ad0c826a2d76748ea4b3ec46ba4df6f82f19dd4bb8465b3e0dcc00f4b"),
    ("IncidentEscalation", "0x093e166d3782b539cb775f185ca10c69fc7248f65712fd64e51785b89648fec3"),
];
