// Generated by scripts/vendor-template-artifacts.sh — do not edit by hand.
//
// Test-only: this table exists to be asserted against, so lib.rs gates it
// behind #[cfg(test)]. Its job is done at test time — if the embedded
// bytecode ever stops matching what the registry pinned, the build fails
// here rather than the factory refusing the deploy in front of a human.
// Each value is the initCodeHash REGISTERED ON CHAIN for that template,
// read from GovernanceTemplateRegistry at vendoring time. The test in
// deploy.rs asserts the embedded artifact hashes to exactly this.
pub const REGISTERED_INIT_CODE_HASHES: &[(&str, &str)] = &[
    ("ThresholdApproval", "0x00b47af3274361da03ed9289b2fc624d1be6d67be2efa925ec82a7b23c16cf00"),
    ("ClassificationGate", "0x28a8469e93680b108bc7297f33b8450372f15b71647ba7fb770b336dd544fc84"),
    ("BudgetedAutonomy", "0xfff789db4ef080711f9ea1cc389932043fac900aeba3e388ec9d1c56d3619953"),
    ("SegregationOfDuties", "0x736c23ede9e130c42af8cfdb87c0b9ccc5946f72528c1ba68c78560cc73c9b79"),
    ("TimeBoundedElevation", "0x560ed4d97e847e2b8373a69e3e648e86b95561035eb86992eab1d87a96b226ed"),
    ("ChangeControlBoard", "0x551a2885519edbf572dc5278033a214583086b4c72bf6fe20b2e3ae9322ecc84"),
    ("SupplierAdmission", "0x592ff476cd69a74cc5035f549f9470b6e7d4eb1708b0c5da303c4ca42c0c213f"),
    ("IncidentEscalation", "0x093e166d3782b539cb775f185ca10c69fc7248f65712fd64e51785b89648fec3"),
];
